CREATE TABLE News (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  companyname varchar NOT NULL,
  topic varchar NOT NULL,
  title varchar NOT NULL,
  link varchar NOT NULL,
  context varchar NOT NULL,
  keywords varchar[]
);
