ALTER TABLE News DROP COLUMN keywords;
ALTER TABLE News ADD COLUMN post_time timestamp NOT NULL;
ALTER TABLE News RENAME COLUMN companyname TO company_name;

CREATE TABLE NewsKeyword (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  news_id int NOT NULL,
  keyword varchar NOT NULL
);

CREATE TABLE Users (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  acoount_id varchar NOT NULL,
  password varchar NOT NULL,
  name varchar NOT NULL
);

CREATE TABLE Summarize (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id int NOT NULL,
  summarize varchar NOT NULL
);

ALTER TABLE NewsKeyword ADD FOREIGN KEY (news_id) REFERENCES News (id);

ALTER TABLE Summarize ADD FOREIGN KEY (user_id) REFERENCES Users (id);
